## HTML output utilities.
## Provides functions to generate HTML reports with embedded SVG charts.
import std/[strutils]

proc escapeHTML*(value: string): string =
  ## Escape special characters for HTML output.
  result = value
  result = result.replace("&", "&amp;")
  result = result.replace("<", "&lt;")
  result = result.replace(">", "&gt;")
  result = result.replace("\"", "&quot;")
  result = result.replace("'", "&#39;")

proc htmlHeader*(title: string): string =
  ## Generate HTML document header.
  return """<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>""" & escapeHTML(title) & """</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 20px; background: #f5f5f5; }
    h1 { color: #333; border-bottom: 2px solid #4a90d9; padding-bottom: 10px; }
    h2 { color: #555; margin-top: 30px; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #4a90d9; color: white; font-weight: bold; }
    tr:hover { background: #f0f0f0; }
    .stat-positive { color: #2ecc71; }
    .stat-negative { color: #e74c3c; }
    .stat-neutral { color: #7f8c8d; }
    .chart-container { margin: 20px 0; text-align: center; }
    .legend { margin: 10px 0; font-size: 14px; }
    .legend-item { display: inline-block; margin-right: 20px; }
    .legend-color { display: inline-block; width: 12px; height: 12px; margin-right: 5px; vertical-align: middle; }
    footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 12px; }
  </style>
</head>
<body>
"""

proc htmlFooter*(): string =
  ## Generate HTML document footer.
  return """
<footer>
  Generated by data_report_cli - xiangke game data report tool
</footer>
</body>
</html>
"""

proc htmlTable*(headers: seq[string], rows: seq[seq[string]], cssClass: string = ""): string =
  ## Generate an HTML table.
  var html = "<table"
  if cssClass.len > 0:
    html &= " class=\"" & cssClass & "\""
  html &= ">\n"
  
  # Header
  html &= "  <thead>\n    <tr>\n"
  for h in headers:
    html &= "      <th>" & escapeHTML(h) & "</th>\n"
  html &= "    </tr>\n  </thead>\n"
  
  # Body
  html &= "  <tbody>\n"
  for row in rows:
    html &= "    <tr>\n"
    for cell in row:
      html &= "      <td>" & escapeHTML(cell) & "</td>\n"
    html &= "    </tr>\n"
  html &= "  </tbody>\n"
  
  html &= "</table>\n"
  return html

proc htmlSection*(title: string, content: string): string =
  ## Wrap content in a section with a heading.
  return "<h2>" & escapeHTML(title) & "</h2>\n" & content

proc writeHTML*(filename: string, html: string) =
  ## Write HTML content to a file.
  try:
    writeFile(filename, html)
    echo "HTML report written to: ", filename
  except IOError:
    echo "Error: Cannot write to file: ", filename
